
token_key: yawei is the honorest in the worlds
url_prefix: /api/v1
domain_port: http://www.datasview.com:8000
auth_test_mode: True
ip_test_mode: True
allow_link_ip:
- 35.241.66.226

mods: 
  fmod: 
    name: fmod
    status: unused
    version: 1
    has_mdl: False
    tags: 
    - 模组的名字
    
# 用来存放站点地图所连接的数据库
site_maps:
  single_sites:
    index: 
    - link: /
      lastmod: 2021-2-6
      changefreq: weekly
      priority: 1.0
  db_sites: 
    f-mod:
      mdls: 
      - table: F-mod
        link_key: link
        lastmod_key: update_date
        prefix: fmod/ # 前缀
      priority: 0.9
      changefreq: daily
  


